SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS`avaliacoes`;
DROP TABLE IF EXISTS`denuncias`;
DROP TABLE IF EXISTS `departamentos`;
DROP TABLE IF EXISTS `disciplinas`;
DROP TABLE IF EXISTS `disciplina_professor`;
DROP TABLE IF EXISTS `professores`;
DROP TABLE IF EXISTS `turmas`;
DROP TABLE IF EXISTS `usuarios`;
DROP TABLE IF EXISTS `usuarios_pictures`;
DROP VIEW  IF EXISTS `view_avaliacoes_usuarios`;
DROP PROCEDURE IF EXISTS `getProfessoresByDisciplina`;
SET FOREIGN_KEY_CHECKS = 1;